### PR TITLE
Merge to recent RNN changes, some cleanup

### PR DESCRIPTION
**Pull request by dguest**
Some things from my RNN branch didn't make it into your GRU changes, and I also tried to cut down the duplicated code the GRUs added where it was easy. If these changes work with your branch I can merge your other pull request.

### CODE REVIEW

**Comment by mickypaganini** [comment]
- What's the point of enforcing python3? Everything works fine with python2.7 too
- Isn't it an overkill to have that mini-function to check the keras version? What's wrong with just checking if it starts with "1.0."? It looks so much nicer to read than having to go read the function and figure out what everything is.
- Thanks for cleaning up the "components" stuff.
- Everything still works

**Comment by mickypaganini** [comment]
- Also, so far you only check for 'miscellaneous' and 'sort_order', but we don't use them for actual sorting yet, right? Or did I miss it?

**Comment by dguest** [comment]
- Because I wrote it in python 3. You can call `python keras2json.py` with any version of python you like, so it's not really enforced. If you change to `/usr/bin/env python` [nearly every system will call python 2, but it's not completely clear](https://www.python.org/dev/peps/pep-0394/) what this will do in the future. I think it's better to specify the language and let the user override it at her own peril.
- What I did is totally overkill. But checking that a string starts with "1.0" isn't the same thing as checking that "1.0" is in the string. Actually we could probably just use `if _version.startswith('1.0')`.
- I think I'm going to make the `parse_json` function more general so that it just eats whatever components you give it and we don't have to have a special case for each type of layer. That's why I didn't like having one component map for each type of layer.
- Awesome
- I didn't want to implement the sorting in this code because that seemed sort of application specific. Actually [the variable should be "sort_by"](https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/JetTagging/JetTagTools/branches/JetTagTools-01-00-85-branch/src/RNNIPTag.cxx#L47).

**Comment by mickypaganini** [comment]
Ok, merged your stuff into mine. That should have automatically updated the other pull request right?
- I like the idea of startwith('1.0')
- I can modify the name to 'sort_by'. Is the point of having the list of variable names and the variable used for sorting just for the user's information? We really can put no check in place on whether the user is actually sorting tracks by the right variable and feeding in inputs with the correct variable order.

**Pull request merged**
